In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
s= pd.Series(9)
dates= pd.date_range('20130612',periods=6 )
dates

import catboost
import numpy as np
from catboost import CatBoostRegressor,Pool,CatBoostClassifier

In [5]:
def l(*t):
    print(t)
    
def exportCsv(path,count):
    l('opening '+path)
    r=open(path, 'r')
    l('opened')
    #i=-1
    for i,line in enumerate(r):
        colls=line.replace('\n','').split(',')
     #   i+=1
        #print(line)
        if(i==0):
            l([{indx,col} for indx,col in enumerate(colls)])
            #continue
        yield colls#[x for indx,x in enumerate(colls) if indx!=11]
        
        if(i>count):
            l('break len=',i)
        #    break

from glob import glob
def combineScvs(pathMatch,n):
    for fle in glob(pathMatch):
        l(fle)
        l(type(fle))
        yield exportCsv(fle,n)
    # f = np.load.. 
csvYield= exportCsv('qwe000000000000.csv',10000000)
data=[line for line in csvYield]
l('длина:',len(data),' тип',type(data))
data[0]

#combineScvs('qwe0000000000*[0-9].csv',100)

('opening qwe000000000000.csv',)
('opened',)
([{0, 'vendor_id'}, {1, 'pickup_datetime'}, {2, 'dropoff_datetime'}, {3, 'pickup_longitude'}, {4, 'pickup_latitude'}, {'dropoff_longitude', 5}, {'dropoff_latitude', 6}, {'rate_code', 7}, {8, 'passenger_count'}, {9, 'trip_distance'}, {'payment_type', 10}, {'fare_amount', 11}, {12, 'extra'}, {'mta_tax', 13}, {'imp_surcharge', 14}, {'tip_amount', 15}, {16, 'tolls_amount'}, {17, 'total_amount'}, {18, 'store_and_fwd_flag'}],)
('длина:', 999915, ' тип', <class 'list'>)

['vendor_id',
 'pickup_datetime',
 'dropoff_datetime',
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'rate_code',
 'passenger_count',
 'trip_distance',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'imp_surcharge',
 'tip_amount',
 'tolls_amount',
 'total_amount',
 'store_and_fwd_flag']

In [4]:
for line in data:
    if(len(line)!=len(data[1])):
        l(line)
len(data[1])
pd.read_csv('qwe000000000000.csv')
#import tensorflow as tf
#tf.data.TextLineDataset('qwe.txt').map(lambda line: tf.decode_csv(line,))

(['CMT', '2010-02-28 15:41:54 UTC', '2010-02-28 16:00:01 UTC', '-73.997086', '40.763702', '-73.955491', '40.776715', '1', '1', '3.5', 'CAS', '12.5', '0', '0.5', '', '0', '0', '13', '"', '"'],)
(['CMT', '2010-03-18 15:53:00 UTC', '2010-03-18 16:00:05 UTC', '-73.983318', '40.767275', '-73.988711', '40.777759', '1', '1', '1.1', 'Cas', '6.1', '0', '0.5', '', '0', '0', '6.6', '"', '"'],)
(['CMT', '2010-02-22 13:12:25 UTC', '2010-02-22 13:31:23 UTC', '-73.870708', '40.773878', '-73.992817', '40.753316', '1', '1', '9', 'CAS', '22.1', '0', '0.5', '', '0', '0', '22.6', '"', '"'],)
(['CMT', '2010-03-13 15:53:52 UTC', '2010-03-13 16:00:34 UTC', '-73.997777', '40.74492', '-73.979712', '40.738025', '1', '1', '1.1', 'Cas', '5.7', '0', '0.5', '', '0', '0', '6.2', '"', '"'],)

,vendor_id,pickup_datetime,dropoff_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,rate_code,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,imp_surcharge,tip_amount,tolls_amount,total_amount,store_and_fwd_flag
0,CMT,2010-03-04 00:35:16 UTC,2010-03-04 00:35:47 UTC,-74.035201,40.721548,-74.035201,40.721548,1.0,1,0.00,Cas,0.00,0.0,0.0,NaN,0.00,0.00,0.00,0
1,CMT,2010-03-15 17:18:34 UTC,2010-03-15 17:18:35 UTC,0.000000,0.000000,0.000000,0.000000,1.0,1,0.00,Cas,0.00,0.0,0.0,NaN,0.00,0.00,0.00,0
2,VTS,2015-03-18 01:07:02 UTC,2015-03-18 01:07:07 UTC,0.000000,0.000000,0.000000,0.000000,1.0,5,0.00,CRD,0.00,0.0,0.0,0.3,0.00,0.00,0.00,N
3,VTS,2015-03-09 18:24:03 UTC,2015-03-09 18:25:37 UTC,-73.937248,40.758202,-73.937263,40.758190,1.0,1,0.00,CRD,0.00,0.0,0.0,0.3,0.00,0.00,0.00,N
4,CMT,2010-03-06 06:33:41 UTC,2010-03-06 06:36:06 UTC,-73.785514,40.645400,-73.784564,40.648681,1.0,2,4.10,Cas,0.00,0.0,0.0,NaN,0.00,0.00,0.00,0
5,CMT,2013-08-07 00:42:45 UTC,2013-08-07 00:58:43 UTC,-74.025817,40.763044,-74.046752,40.783240,5.0,1,4.80,CSH,0.00,0.0,0.0,NaN,0.00,0.00,0.00,N
6,VTS,2015-04-26 02:56:37 UTC,2015-04-26 03:00:01 UTC,-73.987656,40.771656,-73.987556,40.771751,1.0,1,0.00,CSH,0.00,0.0,0.0,0.3,0.00,0.00,0.00,N
7,VTS,2015-04-29 18:45:03 UTC,2015-04-29 18:49:01 UTC,0.000000,0.000000,0.000000,0.000000,1.0,1,1.00,CSH,0.00,0.0,0.0,0.0,0.00,0.00,0.00,N
8,CMT,2010-03-11 21:24:48 UTC,2010-03-11 21:46:51 UTC,-74.571511,40.910800,-74.628928,40.964321,1.0,1,68.40,Dis,0.00,0.0,0.0,NaN,0.00,0.00,0.00,0
9,CMT,2013-08-24 01:58:23 UTC,2013-08-24 01:58:23 UTC,-73.972171,40.759439,0.000000,0.000000,5.0,4,0.00,CSH,0.00,0.0,0.0,NaN,0.00,0.00,0.00,N
10,CMT,2015-01-27 18:24:31 UTC,2015-01-27 18:24:46 UTC,-73.983391,40.684906,-73.983391,40.684906,5.0,0,1.10,CRD,0.00,0.0,0.0,0.3,29.70,0.00,30.00,N
11,CMT,2015-02-07 00:05:40 UTC,2015-02-07 00:40:35 UTC,-73.986473,40.745235,-74.125824,40.649357,5.0,1,12.80,CRD,0.00,0.0,0.0,0.3,0.00,75.45,75.75,N
12,CMT,2015-01-11 15:52:20 UTC,2015-01-11 15:54:50 UTC,-73.990921,40.771244,-73.998123,40.761108,5.0,2,8.10,NOC,0.00,0.0,0.0,0.3,0.00,0.00,0.30,N
13,CMT,2015-01-25 02:13:45 UTC,2015-01-25 02:14:28 UTC,-73.879440,40.828388,-73.878922,40.828487,5.0,1,9.30,CSH,0.00,0.0,0.0,0.3,0.00,0.00,0.30,N
14,CMT,2015-06-12 04:44:54 UTC,2015-06-12 04:50:02 UTC,-73.995995,40.738575,-73.994545,40.752754,5.0,2,1.30,NOC,0.00,0.0,0.0,0.3,0.00,0.00,0.30,N
15,CMT,2015-06-07 22:25:48 UTC,2015-06-07 22:27:02 UTC,-74.001854,40.740406,-74.004524,40.741680,5.0,2,0.20,NOC,0.00,0.0,0.0,0.3,0.00,0.00,0.30,N
16,CMT,2015-06-28 09:50:52 UTC,2015-06-28 09:52:46 UTC,-73.836395,40.826229,-73.836189,40.849586,5.0,2,1.60,DIS,0.00,0.0,0.0,0.3,0.00,0.00,0.30,N
17,CMT,2015-05-05 23:03:36 UTC,2015-05-05 23:43:18 UTC,-73.971527,40.757408,-74.049431,40.790279,5.0,2,7.10,NOC,0.00,0.0,0.0,0.3,0.00,9.75,10.05,N
18,CMT,2015-02-20 22:57:17 UTC,2015-02-20 23:11:41 UTC,-74.008736,40.710773,-74.030327,40.739285,5.0,2,4.50,DIS,0.00,0.0,0.0,0.3,0.00,9.75,10.05,N
19,CMT,2015-06-09 21:54:14 UTC,2015-06-09 22:21:34 UTC,-73.987732,40.752335,-74.035713,40.747341,5.0,1,4.10,DIS,0.00,0.0,0.0,0.3,0.00,9.75,10.05,N
20,VTS,2009-03-06 06:46:00 UTC,2009-03-06 06:46:00 UTC,-74.000282,40.739773,-74.000282,40.739773,NaN,1,0.00,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
21,VTS,2009-01-11 18:01:00 UTC,2009-01-11 18:01:00 UTC,-73.845082,40.692222,-73.845082,40.692222,NaN,2,0.00,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
22,DDS,2009-01-07 11:54:30 UTC,2009-01-07 11:54:47 UTC,-73.880578,40.769536,-73.878493,40.770667,NaN,1,0.00,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
23,VTS,2009-05-16 13:39:00 UTC,2009-05-16 13:40:00 UTC,-73.783258,40.648627,-73.784010,40.648638,NaN,1,0.08,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
24,DDS,2009-06-20 18:56:26 UTC,2009-06-20 18:57:00 UTC,-73.977654,40.758487,-73.976328,40.758038,NaN,1,0.00,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
25,VTS,2009-03-08 07:49:00 UTC,2009-03-08 07:50:00 UTC,-73.946930,40.776232,-73.945627,40.775215,NaN,1,0.14,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
26,VTS,2009-04-22 09:25:00 UTC,2009-04-22 09:26:00 UTC,-74.016753,40.708292,-74.016967,40.709045,NaN,1,0.08,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
27,VTS,2009-08-20 07:40:00 UTC,2009-08-20 08:08:00 UTC,-73.950743,40.770763,-73.950743,40.770763,NaN,1,0.01,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
28,VTS,2010-05-21 08:27:00 UTC,2010-05-22 00:00:00 UTC,0.000000,0.000000,-73.998703,40.764448,1.0,1,0.00,CAS,2.50,0.0,0.0,NaN,0.00,0.00,2.50,NaN
29,VTS,2009-01-09 11:11:00 UTC,2009-01-09 11:12:00 UTC,-73.982508,40.769120,-73.983742,40.769113,NaN,5,0.07,CSH,2.50,0.0,NaN,NaN,0.00,0.00,2.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999884,CMT,2009-01-30 20:50:24 UTC,2009-01-30 21:18:26 UTC,-73.967875,40.792920,-73.830140,40.872361,NaN,1,12.30,CSH,29.80,0.0,NaN,NaN,0.00,0.00,29.80,NaN
999885,CMT,2009-01-24 20:45:03 UTC,2009-01-24 21:20:15 UTC,-74.009983,40.733145,-73.936703,40.849264,NaN,1,10.40,CSH,29.80,0.0,NaN,NaN,0.00,0.00,29.80,NaN
999886,CMT,2009-02-07 00:46:38 UTC,2009-02-07 01:24:48 UTC,-73.992441,40.763366,-73.979975,40.663616,NaN,1,10.50,CSH,29.80,0.0,NaN,NaN,0.00,0.00,29.80,NaN
999887,CMT,2009-01-24 04:08:37 UTC,2009-01-24 04:29:46 UTC,-73.982450,40.764025,-73.811068,40.694165,NaN,1,12.50,CSH,29.80,0.0,NaN,NaN,0.00,0.00,29.80,NaN
999888,CMT,2009-02-24 23:04:24 UTC,2009-02-24 23:27:14 UTC,-73.974269,40.755427,-74.032142,40.632576,NaN,1,12.80,NOC,29.80,0.0,NaN,NaN,0.00,0.00,29.80,N
999889,CMT,2009-02-12 21:35:00 UTC,2009-02-12 22:04:33 UTC,-73.985596,40.723283,-73.982347,40.607759,NaN,1,12.10,CRD,29.80,0.0,NaN,NaN,1.00,0.00,30.80,N
999890,CMT,2009-01-05 22:22:09 UTC,2009-01-05 22:45:58 UTC,-73.947248,40.779840,-74.013169,40.642396,NaN,1,13.60,CRD,31.80,0.0,NaN,NaN,4.77,0.00,36.57,NaN
999891,CMT,2009-01-25 03:33:00 UTC,2009-01-25 04:01:35 UTC,-74.002582,40.749943,-73.985356,40.616140,NaN,2,12.50,CSH,31.80,0.0,NaN,NaN,0.00,0.00,31.80,NaN
999892,CMT,2009-03-10 23:25:38 UTC,2009-03-10 23:54:11 UTC,-73.789067,40.641700,-73.977036,40.664463,NaN,2,13.10,CSH,31.80,0.0,NaN,NaN,0.00,0.00,31.80,N
999893,CMT,2012-07-01 13:10:30 UTC,2012-07-01 13:11:47 UTC,-73.997092,40.766946,-73.997092,40.766946,5.0,1,0.00,CRD,39.60,0.0,0.0,NaN,0.00,0.00,39.60,N
999894,CMT,2015-03-06 14:38:07 UTC,2015-03-06 14:38:07 UTC,0.000000,0.000000,0.000000,0.000000,99.0,1,0.00,CRD,79.20,0.0,0.5,0.3,0.00,0.00,80.00,N
999895,CMT,2011-10-23 18:56:03 UTC,2011-10-23 20:19:11 UTC,-73.789825,40.646850,-73.990037,40.806591,4.0,1,25.50,CSH,67.70,0.0,0.5,NaN,0.00,14.30,82.50,N
999896,VTS,2010-01-22 22:54:00 UTC,2010-01-22 23:49:00 UTC,-73.987975,40.737538,-74.005908,40.647017,1.0,5,30.48,CAS,67.70,0.5,0.5,NaN,0.00,0.00,68.70,NaN
999897,VTS,2011-10-16 08:04:00 UTC,2011-10-16 08:38:00 UTC,-73.997000,40.751218,-74.173300,40.736010,4.0,1,15.74,CRD,67.70,0.0,0.5,NaN,0.00,9.50,77.70,NaN
999898,VTS,2011-04-26 21:38:00 UTC,2011-04-26 22:18:00 UTC,-73.862745,40.768897,-73.822935,41.056277,4.0,1,26.92,CSH,75.70,0.5,0.5,NaN,0.00,4.80,81.50,NaN
999899,CMT,2011-05-31 22:01:59 UTC,2011-05-31 22:28:43 UTC,-73.776822,40.645442,-73.589855,40.746053,4.0,1,21.40,CRD,75.70,0.5,0.5,NaN,10.00,0.00,86.70,N
999900,VTS,2011-09-17 15:20:00 UTC,2011-09-17 17:12:00 UTC,-73.961620,40.798592,-74.181797,40.564825,1.0,2,34.28,CSH,87.70,0.0,0.5,NaN,0.00,14.40,102.60,NaN
999901,VTS,2010-04-22 15:37:00 UTC,2010-04-22 17:06:00 UTC,-73.786042,40.641805,-73.825108,40.978408,4.0,5,30.97,CAS,87.70,0.0,0.5,NaN,0.00,0.00,88.20,NaN
999902,VTS,2014-12-30 21:56:00 UTC,2014-12-30 21:56:00 UTC,0.000000,0.000000,0.000000,0.000000,5.0,1,0.00,CRD,32.01,0.0,0.0,NaN,0.00,0.00,32.01,NaN
999903,CMT,2014-11-16 14:28:42 UTC,2014-11-16 15:16:13 UTC,-73.782133,40.644838,-73.987104,40.756566,2.0,2,18.20,CSH,52.01,0.0,0.5,NaN,0.00,5.33,57.84,N
999904,CMT,2010-01-29 07:01:54 UTC,2010-01-29 07:02:59 UTC,-74.113857,40.815270,-74.113857,40.815270,1.0,1,0.00,Cre,60.01,0.0,0.0,NaN,0.00,0.00,60.01,0
999905,VTS,2010-02-16 07:24:00 UTC,2010-02-16 07:40:00 UTC,0.000000,0.000000,0.000000,0.000000,1.0,1,0.13,CRD,9.69,0.0,0.5,NaN,0.80,0.00,10.99,NaN
999906,VTS,2010-10-31 00:32:00 UTC,2010-10-31 00:44:00 UTC,0.000000,0.000000,0.000000,0.000000,1.0,1,0.26,CRD,9.69,0.5,0.5,NaN,1.50,0.00,12.19,NaN
999907,VTS,2011-08-02 20:57:00 UTC,2011-08-02 21:11:00 UTC,-73.990340,40.719412,-74.015163,40.709903,1.0,1,0.26,CRD,9.69,0.5,0.5,NaN,2.00,0.00,12.69,NaN
999908,VTS,2011-03-23 20:57:00 UTC,2011-03-23 21:13:00 UTC,-74.007617,40.740887,-73.991902,40.717605,1.0,1,0.24,CRD,9.69,0.5,0.5,NaN,2.00,0.00,12.69,NaN
999909,VTS,2011-10-28 16:46:00 UTC,2011-10-28 17:03:00 UTC,-73.976902,40.774723,-73.974117,40.765215,1.0,1,0.14,CRD,9.69,1.0,0.5,NaN,2.00,0.00,13.19,NaN
999910,VTS,2012-10-25 12:21:00 UTC,2012-10-25 12:56:00 UTC,-73.873838,40.773853,-73.587550,40.723847,5.0,1,25.05,CRD,117.77,0.0,0.5,NaN,15.00,0.00,133.27,NaN
999911,CMT,2015-05-23 16:22:08 UTC,2015-05-23 16:22:44 UTC,-73.996506,40.746071,-73.996422,40.746078,5.0,1,0.00,CRD,58.34,0.0,0.0,0.3,10.00,0.00,68.64,N
999912,CMT,2015-06-04 00:35:04 UTC,2015-06-04 00:35:33 UTC,-73.784973,40.785900,-73.784958,40.785912,5.0,1,0.00,CSH,52.84,0.0,0.0,0.3,0.00,0.00,53.14,N
999913,CMT,2009-04-05 21:00:01 UTC,2009-04-05 21:07:28 UTC,-73.954192,40.787271,-73.976447,40.764421,NaN,2,2.30,CSH,8.23,0.0,NaN,NaN,0.00,0.00,8.23,N

In [ ]:

datapd=pd.Series(data)
datapd.drop(0)
datapd.head()
datapd.dtypes
columns

In [ ]:
pool=Pool(datapd,cat_features=[0, 1, 2, 3, 4, 5,10,18])
model=CatBoostClassifier()
#np.loadtxt('qwe.txt',)